TAKI = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgHHgHHHHHHHHHHMgmHMgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHH@HH@HH@@H@@HH@HMHggmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHH@@H@HH@@HH@H@@HHHHHMmHgggHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH@H@H@H@@HH@HM@HH@@@H@@HHHHH@HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHM@@@MMMHHMHHHHHH@@H@H@H@NQW@M@@HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMHHHWQkH@@HMM@@HHHHHH@HH@@HH@@HHMmkWHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBuXdH@@H@H@HM@@H@HHHHHM@@HH@HMH@@H@@MmXuMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8XdH@@H@H@@H@@H@@@HMH#HHMMHM@@HMM@@H@H@HMkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBXd@@@MHM@@@@HMHM@@H@HMMHHHHHHMH@@@HH@@H@@H@HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSXH@@MHMMM@@@@M@H@M@@H@MM@MMHHHHHHM@@@@H@HH@HMHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSXH@@MHMM@@@@HHHMH@@H@HM@MM@H@MMHHHHHMHHM@@@@HMHqMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk@@@HMH@@@@@HHMMUMMM@HHM@@MHM@fW@@MHH@MHM@H@@HMMHHHMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNbH@MHH@@@@@HHMH3_HvH@HH@M@@M/4H-7M@MHM@HH@HM@@HMHMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNW@M@M@@@@HHM4$((dmXH@@H@@gm6-dHmQH@HMMMHM@M@@HHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNbH@H@@@@MHMh?=!..1.-7HWH@@q}((-z.-_?WM@MHMH@@MHNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHH@@@@H@H@b(dVY""7TTYhx-XgHBT71(<?7T9W@HHMHH@MHMHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHW@H@@@H@@@F_.JTTW9Y7!-Y""49<._!+WVYT<-JH@HH@@NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHH@@H@MH@@@L.   ?<<! .<._._.1.. _~?_  .(MHHM@MHMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHH@@HMMHH@N_.......`..`.~`......`.`.....J@@@HNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMN@M#H@@@H;..`..`..`..`_.`.```..`.`..-g@MM=dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNMb-TTHgh_..``.`..`..<.`..`..`..._?T4II<.JMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMm.-=I{__........._O........`....(z<?!(MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-_?-......`.......`..`...`..-!.(jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm(m-.......`...............(NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN,....._--_..-_---...._JMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMe_.......---_....._(MMHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMz1-............_(IdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0llI-_..~..~._(OllMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRllllzi-~.~~(llll<MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9=_?=llltOtlOlll<~.7WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM^`___~<1llllllz<_.__!`UMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$````` ~__~?<<~___~```` MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMF`````````` +:-``````````.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHkpr```````` ,~_` <.````.``.`(bHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmqqbr...`..`.~. ~.``.<..`..`..XbkqqHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""


WHAT = r"""
__          __ _    _           _______
\ \        / /| |  | |    /\   |__   __|
 \ \  /\  / / | |__| |   /  \     | |
  \ \/  \/ /  |  __  |  / /\ \    | |
   \  /\  /   | |  | | / ____ \   | |
    \/  \/    |_|  |_|/_/    \_\  |_|
"""

IS = r"""
 _____   _____
|_   _| / ____|
  | |  | (___
  | |   \___ \
 _| |_  ____) |
|_____||_____/
"""

THIS = r"""
 _______  _    _  _____   _____
|__   __|| |  | ||_   _| / ____|
   | |   | |__| |  | |  | (___
   | |   |  __  |  | |   \___ \
   | |   | |  | | _| |_  ____) |
   |_|   |_|  |_||_____||_____/
"""

NANDESUKA = r"""
   ■■             ■                          ■          ■      
   ■             ■■         ■■■■■■■■         ■          ■      
 ■■■■■  ■■       ■        ■■■   ■      ■■■■■■■■■■      ■■   ■  
  ■■     ■■     ■■             ■   ■         ■      ■■■■■■■  ■ 
  ■    ■        ■             ■   ■ ■     ■■■■         ■  ■  ■■
  ■    ■       ■■■■           ■    ■      ■  ■        ■■  ■   ■
 ■     ■       ■■  ■          ■           ■  ■        ■   ■    
■■  ■■■■      ■■   ■   ■      ■           ■■■■        ■   ■    
    ■  ■■■    ■    ■  ■       ■■            ■■       ■    ■    
    ■■■■     ■■    ■■■          ■■■        ■■        ■ ■■■     
                                          ■                    
"""

KORE = r"""
■■■■■■■■■     ■       
       ■■     ■       
       ■■     ■       
       ■■     ■       
       ■■     ■     ■■
       ■■     ■    ■■ 
       ■■     ■   ■■  
■■■■■■■■■     ■■■■    
       ■■     ■■■     
"""